# Generated by Django 3.2.5 on 2021-07-15 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='priority',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='priority',
            name='rank',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='todotask',
            name='comment',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='todotask',
            name='project',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='todotask',
            name='task',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
