# Generated by Django 3.2.5 on 2021-07-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_auto_20210715_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='reminder',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='todotask',
            name='time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
