# Generated by Django 3.2.5 on 2021-07-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0002_label_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='reminder',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todotask',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
