# Generated by Django 3.2.5 on 2021-07-17 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20210715_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todoList.label'),
        ),
    ]
