# Generated by Django 3.2.5 on 2021-07-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0003_auto_20210722_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='color',
        ),
    ]
