# Generated by Django 3.2.5 on 2021-07-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0005_auto_20210725_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name_plural': 'Priorities'},
        ),
    ]
