# Generated by Django 3.2.5 on 2021-07-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoList', '0006_alter_priority_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
